[build]
  command = "echo 'Building...' && exit 0"  # Simple commande de construction
  publish = "public"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["node-fetch"]

[[redirects]]
  from = "/recettes/*-id=*"
  to = "/recettes/recette.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
