[build]
  command = "echo 'Building...' && exit 0"
  publish = "."

[functions]
  directory = "netlify/functions"
  external_node_modules = ["node-fetch", "airtable"]


[[headers]]
for = "/*"
[headers.values]
Set-Cookie = "SameSite=None; Secure"
