[build]
  command = "echo 'Building...' && exit 0"
  publish = "."

[functions]
  directory = "netlify/functions"
  external_node_modules = ["node-fetch", "google-auth-library", "airtable"]

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "
    default-src 'self'; 
    img-src 'self' https://orpps.netlify.app/; 
    style-src 'self' https://orpps.netlify.app 'unsafe-inline'; 
    script-src 'self' https://identity.netlify.com 'unsafe-inline'; 
    connect-src 'self' https://identity.netlify.com"
